### ISSUE TITLE
Volunteer notification on shift assignment

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#205] opened 2015-10-23 16:00 UTC
If a volunteer is (self- or management-) assigned to a shift a notification 
email should be send to users email address.

Especially when managers can assign users to shifts it's important to notify users about assignment.

**Comment by klinger** [comment] 2015-12-07 19:24
How far is the implementation of this @christophmeissner ?
You may want describe this as task to and unassign you. Seems to me like an easy/small task for beginners.

**Comment by christophmeissner** [comment] 2022-03-26 13:17
duplicate of #475

**Closed by christophmeissner** 2022-03-26 13:17 UTC
Labels: Enhancement
